-- ============================================================
-- f0_process_codes: 식약처 공식 제조공정 코드 테이블 (211개)
-- 담당: f0 (경아)
-- 생성일: 2026-04-17
-- ============================================================

CREATE TABLE IF NOT EXISTS f0_process_codes (
    id          BIGSERIAL PRIMARY KEY,
    code        TEXT NOT NULL UNIQUE,      -- 예: '8', 'A6', 'F14'
    name_ko     TEXT NOT NULL,             -- 예: '가열', '혼합', '효소처리(트랜스글루타미나아제)'
    code_type   TEXT NOT NULL              -- 'numeric' | 'alpha'
                CHECK (code_type IN ('numeric', 'alpha')),
    updated_at  TIMESTAMPTZ DEFAULT now()
);

-- 검색 인덱스
CREATE INDEX IF NOT EXISTS idx_f0_process_codes_name_ko
    ON f0_process_codes (name_ko);

CREATE INDEX IF NOT EXISTS idx_f0_process_codes_code_type
    ON f0_process_codes (code_type);

-- 전문 검색용 인덱스 (pg_trgm 확장 필요 — 001_pg_trgm_extension.sql 먼저 실행)
CREATE INDEX IF NOT EXISTS idx_f0_process_codes_name_trgm
    ON f0_process_codes USING gin (name_ko gin_trgm_ops);

-- ============================================================
-- 초기 데이터 INSERT (식약처 공식 211개)
-- ============================================================

INSERT INTO f0_process_codes (code, name_ko, code_type) VALUES
-- 숫자 코드 (1~102)
('1',   '원료',             'numeric'),
('2',   '가당',             'numeric'),
('3',   '가미',             'numeric'),
('4',   '가수',             'numeric'),
('5',   '가수분해',         'numeric'),
('6',   '가압',             'numeric'),
('7',   '예열',             'numeric'),
('8',   '가열',             'numeric'),
('9',   '가염',             'numeric'),
('10',  '건조',             'numeric'),
('11',  '굽기',             'numeric'),
('12',  '볶기',             'numeric'),
('13',  '결정화',           'numeric'),
('14',  '경화',             'numeric'),
('15',  '권체',             'numeric'),
('16',  '균질',             'numeric'),
('17',  '냉각',             'numeric'),
('18',  '냉동',             'numeric'),
('19',  '냉장',             'numeric'),
('20',  '재농축',           'numeric'),
('21',  '농축',             'numeric'),
('22',  '담금',             'numeric'),
('23',  '당화',             'numeric'),
('24',  '롤링',             'numeric'),
('25',  '멸균',             'numeric'),
('26',  '밀봉',             'numeric'),
('27',  '발효',             'numeric'),
('28',  '후발효',           'numeric'),
('29',  '배양',             'numeric'),
('30',  '분리',             'numeric'),
('31',  '분무',             'numeric'),
('32',  '분쇄',             'numeric'),
('33',  '분말',             'numeric'),
('34',  '분해',             'numeric'),
('35',  '불활성화',         'numeric'),
('36',  '사출',             'numeric'),
('37',  '산도조정',         'numeric'),
('38',  '산분해',           'numeric'),
('39',  '살균',             'numeric'),
('40',  '살수',             'numeric'),
('41',  '사별',             'numeric'),
('42',  '수처리',           'numeric'),
('43',  '선별',             'numeric'),
('44',  '성형',             'numeric'),
('45',  '세척',             'numeric'),
('46',  '소성',             'numeric'),
('47',  '수소촉매첨가',     'numeric'),
('48',  '숙성',             'numeric'),
('49',  '쇄련',             'numeric'),
('50',  '알파화',           'numeric'),
('51',  '압연',             'numeric'),
('52',  '압착',             'numeric'),
('53',  '액화',             'numeric'),
('54',  '에스테르교환',     'numeric'),
('55',  '여과',             'numeric'),
('56',  '역삼투',           'numeric'),
('57',  '연곡',             'numeric'),
('58',  '연압',             'numeric'),
('59',  '용제첨가',         'numeric'),
('60',  '용해',             'numeric'),
('61',  '원심분리',         'numeric'),
('62',  '유청',             'numeric'),
('63',  '유탕',             'numeric'),
('64',  '유화',             'numeric'),
('65',  '응고',             'numeric'),
('66',  '이성화',           'numeric'),
('67',  '저장',             'numeric'),
('68',  '전처리',           'numeric'),
('69',  '절단',             'numeric'),
('70',  '절임',             'numeric'),
('71',  '접종',             'numeric'),
('72',  '접착',             'numeric'),
('73',  '정제',             'numeric'),
('74',  '조미',             'numeric'),
('75',  '조유',             'numeric'),
('76',  '주입',             'numeric'),
('77',  '중화',             'numeric'),
('78',  '증류',             'numeric'),
('79',  '증숙',             'numeric'),
('80',  '제국',             'numeric'),
('81',  '착색',             'numeric'),
('82',  '착즙',             'numeric'),
('83',  '채취',             'numeric'),
('84',  '추출',             'numeric'),
('85',  '용매추출',         'numeric'),
('86',  '침수',             'numeric'),
('87',  '침전',             'numeric'),
('88',  '코팅',             'numeric'),
('89',  '커드형성',         'numeric'),
('90',  '탄산가스',         'numeric'),
('91',  '탈검',             'numeric'),
('92',  '탈기',             'numeric'),
('93',  '탈산',             'numeric'),
('94',  '탈색',             'numeric'),
('95',  '탈수',             'numeric'),
('96',  '탈아세틸화',       'numeric'),
('97',  '탈염',             'numeric'),
('98',  '탈지',             'numeric'),
('99',  '탈취',             'numeric'),
('100', '희석',             'numeric'),
('101', '증발',             'numeric'),
('102', '탈랍',             'numeric'),
-- A 계열
('A0',  '계량,측정,무게달기',      'alpha'),
('A1',  '탈피',                     'alpha'),
('A2',  '톰슨처리',                 'alpha'),
('A3',  '포장',                     'alpha'),
('A4',  '표면처리',                 'alpha'),
('A5',  '해동',                     'alpha'),
('A6',  '혼합',                     'alpha'),
('A7',  '효소처리',                 'alpha'),
('A8',  '가압+탈수+원심분리',       'alpha'),
('A9',  '가열+성형',                'alpha'),
-- B 계열
('B0',  '반응',                     'alpha'),
('B1',  '고기분류',                 'alpha'),
('B2',  '공병및공캔준비',           'alpha'),
('B3',  '금속검출검사또는금속검출', 'alpha'),
('B4',  '껍질벗기기',               'alpha'),
('B5',  '껍질제거',                 'alpha'),
('B6',  '끝손질',                   'alpha'),
('B7',  '머리자르기',               'alpha'),
('B8',  '묶음',                     'alpha'),
('B9',  '묻힘',                     'alpha'),
-- C 계열
('C0',  '전환',                     'alpha'),
('C1',  '배수',                     'alpha'),
('C2',  '산염처리',                 'alpha'),
('C3',  '산처리',                   'alpha'),
('C4',  '산화',                     'alpha'),
('C5',  '선적',                     'alpha'),
('C6',  '수정',                     'alpha'),
('C7',  '우지화',                   'alpha'),
('C8',  '운반',                     'alpha'),
-- D 계열
('D0',  '탑재',                     'alpha'),
('D1',  '점검',                     'alpha'),
('D2',  '조림',                     'alpha'),
('D3',  '주사위모양으로베기',       'alpha'),
('D4',  '짓이김',                   'alpha'),
('D5',  '첨가',                     'alpha'),
('D6',  '침포',                     'alpha'),
('D7',  '콘칭',                     'alpha'),
('D8',  '탈메칠화',                 'alpha'),
('D9',  '탈몰드',                   'alpha'),
-- E 계열
('E1',  '토핑',                     'alpha'),
('E2',  '팽윤',                     'alpha'),
('E3',  '포뜨기',                   'alpha'),
('E4',  '품질관리',                 'alpha'),
('E5',  '훈연',                     'alpha'),
('E6',  '충전',                     'alpha'),
('E7',  '칼럼흡착',                 'alpha'),
('E8',  '제습',                     'alpha'),
('E9',  '이온교환',                 'alpha'),
('E10', '아세틸화',                 'alpha'),
-- F 계열 (효소처리 세분류)
('F1',  '효소처리(글루코아밀라아제)',                                                                         'alpha'),
('F2',  '효소처리(글루코오스산화효소)',                                                                       'alpha'),
('F3',  '효소처리(글루코오스이성화효소)',                                                                     'alpha'),
('F4',  '효소처리(디아스타아제)',                                                                             'alpha'),
('F5',  '효소처리(락타아제)',                                                                                 'alpha'),
('F6',  '효소처리(리파아제)',                                                                                 'alpha'),
('F7',  '효소처리(에스테라아제)',                                                                             'alpha'),
('F8',  '효소처리(말토게닉아밀라아제)',                                                                       'alpha'),
('F9',  '효소처리(G4생성효소)',                                                                               'alpha'),
('F10', '효소처리(G3생성효소)',                                                                               'alpha'),
('F11', '효소처리(아밀로글루코시디아제)',                                                                     'alpha'),
('F12', '효소처리(키토사나아제)',                                                                             'alpha'),
('F13', '효소처리(트랜스글루코시다아제)',                                                                     'alpha'),
('F14', '효소처리(트랜스글루타미나아제)',                                                                     'alpha'),
('F15', '효소처리(펙티나아제)',                                                                               'alpha'),
('F16', '효소처리(프로테아제)',                                                                               'alpha'),
('F17', '효소처리(알파-아밀라아제(세균성):Bacillus subtilis 또는 Bacillus Licheniformis 유래)',              'alpha'),
('F18', '효소처리(베타-글루카나아제)',                                                                        'alpha'),
('F19', '효소처리(알파-글루코실전이효소)',                                                                    'alpha'),
('F20', '효소처리(셀룰라아제)',                                                                               'alpha'),
('F21', '효소처리(인베르타아제)',                                                                             'alpha'),
('F22', '효소처리(트립신)',                                                                                   'alpha'),
('F23', '효소처리(아실라제)',                                                                                 'alpha'),
('F24', '효소처리(헤미셀룰라아제)',                                                                           'alpha'),
('F25', '효소처리(포스포리파아제)',                                                                           'alpha'),
('F26', '효소처리(베타-글루코시다아제)',                                                                      'alpha'),
('F27', '효소처리(naringinase)',                                                                              'alpha'),
('F28', '효소처리(cyclodextrin glucanotransferase)',                                                          'alpha'),
('F29', '효소처리(알파 아밀라아제(비세균성):Aspergillus niger 또는 Aspergillus oryzae 유래)',                 'alpha'),
('F30', '효소처리(파파인)',                                                                                   'alpha'),
('F31', '효소처리(자일라나아제)',                                                                             'alpha'),
-- G 계열 (용매추출 세분류)
('G1',  '용매추출(물)',             'alpha'),
('G2',  '용매추출(주정)',           'alpha'),
('G3',  '용매추출(헥산)',           'alpha'),
('G4',  '용매추출(에테르)',         'alpha'),
('G5',  '용매추출(아세톤)',         'alpha'),
('G6',  '용매추출(이소프로필알콜)', 'alpha'),
('G7',  '용매추출(이산화탄소)',     'alpha'),
('G8',  '용매추출(메틸알콜)',       'alpha'),
('G9',  '용매추출(아세톤)',         'alpha'),
('G10', '용매추출(삼염화에틸렌)',   'alpha'),
('G11', '용매추출(염화에틸렌)',     'alpha'),
('G12', '용매추출(초산에틸)',       'alpha'),
('G13', '용매추출(수산화나트륨)',   'alpha'),
('G14', '용매추출(글리세린)',       'alpha'),
-- H 계열
('H1',  '비누화',               'alpha'),
('H2',  '카페인제거',           'alpha'),
-- I 계열
('I1',  '알킬화(alkylation)',   'alpha'),
-- J 계열
('J1',  '표준화',   'alpha'),
('J2',  '교반',     'alpha'),
('J3',  '환원',     'alpha'),
('J4',  '크림화',   'alpha'),
('J5',  '염지',     'alpha'),
('J6',  '유청제거', 'alpha'),
('J7',  '염장',     'alpha'),
('J8',  '동결',     'alpha'),
('J9',  '양념',     'alpha'),
('J10', '용출',     'alpha'),
('J11', '으깨기',   'alpha'),
-- Z 계열
('Z9',  '기타',     'alpha')
ON CONFLICT (code) DO UPDATE
    SET name_ko    = EXCLUDED.name_ko,
        code_type  = EXCLUDED.code_type,
        updated_at = now();
